[package]
name = "kindbot-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
shuttle-rocket = "0.39.0"
shuttle-runtime = "0.39.0"
tokio = "1.26.0"
reqwest = {version = "0.11.24", features=["blocking","json"]}
rocket = {version = "0.5.0", features=["json"]}
